# Generated by Django 5.2 on 2026-03-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='inquiry',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='previous_school',
        ),
        migrations.CreateModel(
            name='AdmissionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('admission_type', models.CharField(choices=[('NEW', 'New'), ('RE_ADMISSION', 'Re-Admission')], default='NEW', max_length=20)),
                ('previously_applied_year', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('scholar_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_meta', to='admissions.inquiry')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admission_meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='admissions.admissionmeta'),
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('guardian_name', models.CharField(max_length=255)),
                ('signature_file', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('declaration_date', models.DateField(auto_now_add=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='admissions.admissionmeta')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_certificate', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('NOT_SUBMITTED', 'Not Submitted')], default='NOT_SUBMITTED', max_length=20)),
                ('previous_marksheet', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('NOT_SUBMITTED', 'Not Submitted')], default='NOT_SUBMITTED', max_length=20)),
                ('student_photos_3', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('NOT_SUBMITTED', 'Not Submitted')], default='NOT_SUBMITTED', max_length=20)),
                ('sc_st_obc_certificate', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('NOT_SUBMITTED', 'Not Submitted')], default='NOT_SUBMITTED', max_length=20)),
                ('parent_affidavit', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('NOT_SUBMITTED', 'Not Submitted')], default='NOT_SUBMITTED', max_length=20)),
                ('scholarship_letter', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('NOT_SUBMITTED', 'Not Submitted')], default='NOT_SUBMITTED', max_length=20)),
                ('transfer_certificate', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('NOT_SUBMITTED', 'Not Submitted')], default='NOT_SUBMITTED', max_length=20)),
                ('form_received_complete', models.BooleanField(default=False)),
                ('received_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_sign_date', models.DateField(blank=True, null=True)),
                ('any_other_details', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklist', to='admissions.admissionmeta')),
            ],
        ),
        migrations.CreateModel(
            name='ParentGuardianDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN_1', 'Guardian 1'), ('GUARDIAN_2', 'Guardian 2')], max_length=20)),
                ('is_single_parent', models.BooleanField(default=False)),
                ('legal_guardian_type', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('educational_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('samagra_number', models.CharField(blank=True, max_length=20, null=True)),
                ('relation_with_student', models.CharField(blank=True, max_length=100, null=True)),
                ('office_shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_details', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parent_photos/')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_guardians', to='admissions.admissionmeta')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_type', models.CharField(choices=[('GOVT', 'Government'), ('PRIVATE', 'Private')], max_length=20)),
                ('apaar_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pen_number', models.CharField(blank=True, max_length=50, null=True)),
                ('class_last_attended', models.CharField(max_length=50)),
                ('session_year', models.CharField(max_length=20)),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('percentage', models.FloatField()),
                ('pass_fail', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previous_academic', to='admissions.admissionmeta')),
            ],
        ),
        migrations.CreateModel(
            name='SiblingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sibling_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('class_current', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=255)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='admissions.admissionmeta')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100)),
                ('ward_no', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(max_length=255)),
                ('village_town', models.CharField(max_length=255)),
                ('tehsil', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=10)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='admissions.admissionmeta')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='admissions.admissionmeta')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC')], max_length=10)),
                ('family_id', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('samagra_id', models.CharField(blank=True, max_length=20, null=True)),
                ('cwsn', models.BooleanField(default=False)),
                ('cwsn_problem_desc', models.TextField(blank=True, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_bio', to='admissions.admissionmeta')),
            ],
        ),
    ]
